spring.application.name=backend
server.port=8080

# CORS
cors.allowed-origins=http://localhost:3000,http://localhost:5173

# JWT Configuration
jwt.secret=94a08da1fecbb6e8b46990538c7b50b2b8004f141203b573e0a298f69165241f
jwt.expiration=86400000

# Firebase
# Make sure to set GOOGLE_APPLICATION_CREDENTIALS environment variable
# to point to your service account key JSON file
